language: node_js
sudo: false
node_js:
  - "8.8.1"
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: 'npm run coveralls'
env:
  - root_url=http://localhost:3000
  - version_url=api/v1
  global:
    - CC_TEST_REPORTER_ID=d602f8dba02afb857c9bbf32d5196d5ecb1b11a2502a1f53c28a1fc6ba56bccf
