language: node_js
sudo: false
node_js:
  - "8.8.1"
install:
  - npm install
cache:
  directories:
    - "node_modules"
script: npm run coverage
after_success: 'npm run coveralls'
env:
  - root_url=http://localhost:3000
  - version_url=api/v1
